import { component$, isDev } from "@builder.io/qwik";
import { QwikCityProvider, RouterOutlet } from "@builder.io/qwik-city";
import { RouterHead } from "./components/router-head/router-head";

import "./global.css";

export default component$(() => {
  /**
   * The root of a QwikCity site always start with the <QwikCityProvider> component,
   * immediately followed by the document's <head> and <body>.
   *
   * Don't remove the `<head>` and `<body>` elements.
   */

  return (
    <QwikCityProvider>
      <head>
        <meta charset="utf-8" />
        {!isDev && (
          <link
            rel="manifest"
            href={`${import.meta.env.BASE_URL}manifest.json`}
          />
        )}
        <link
          rel="preload"
          href={`${import.meta.env.BASE_URL}fonts/BreeSerif-Regular-subset.woff2`}
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href={`${import.meta.env.BASE_URL}fonts/BricolageGrotesque-96ptExtraBold-subset.woff2`}
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href={`${import.meta.env.BASE_URL}fonts/Fraunces-9ptBlack-subset.woff2`}
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href={`${import.meta.env.BASE_URL}fonts/Fraunces-9ptBlackItalic-subset.woff2`}
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href={`${import.meta.env.BASE_URL}fonts/Literata-Italic-subset.woff2`}
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href={`${import.meta.env.BASE_URL}fonts/Literata-Regular-subset.woff2`}
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href={`${import.meta.env.BASE_URL}fonts/Newsreader16pt-Italic-subset.woff2`}
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href={`${import.meta.env.BASE_URL}fonts/Newsreader16pt-Regular-subset.woff2`}
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href={`${import.meta.env.BASE_URL}fonts/Roboto-Italic-subset.woff2`}
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href={`${import.meta.env.BASE_URL}fonts/Roboto-Regular-subset.woff2`}
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href={`${import.meta.env.BASE_URL}fonts/SourceSerif4Italic-Italic-subset.woff2`}
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href={`${import.meta.env.BASE_URL}fonts/SourceSerif4Roman-Regular-subset.woff2`}
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href={`${import.meta.env.BASE_URL}fonts/Spectral-Bold-subset.woff2`}
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href={`${import.meta.env.BASE_URL}fonts/Spectral-BoldItalic-subset.woff2`}
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href={`${import.meta.env.BASE_URL}fonts/Spectral-ExtraBold-subset.woff2`}
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href={`${import.meta.env.BASE_URL}fonts/Spectral-ExtraBoldItalic-subset.woff2`}
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href={`${import.meta.env.BASE_URL}fonts/Spectral-ExtraLight-subset.woff2`}
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href={`${import.meta.env.BASE_URL}fonts/Spectral-ExtraLightItalic-subset.woff2`}
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href={`${import.meta.env.BASE_URL}fonts/Spectral-Italic-subset.woff2`}
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href={`${import.meta.env.BASE_URL}fonts/Spectral-Light-subset.woff2`}
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href={`${import.meta.env.BASE_URL}fonts/Spectral-LightItalic-subset.woff2`}
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href={`${import.meta.env.BASE_URL}fonts/Spectral-Medium-subset.woff2`}
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href={`${import.meta.env.BASE_URL}fonts/Spectral-MediumItalic-subset.woff2`}
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href={`${import.meta.env.BASE_URL}fonts/Spectral-Regular-subset.woff2`}
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href={`${import.meta.env.BASE_URL}fonts/Spectral-SemiBold-subset.woff2`}
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href={`${import.meta.env.BASE_URL}fonts/Spectral-SemiBoldItalic-subset.woff2`}
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href={`${import.meta.env.BASE_URL}fonts/TenorSans-subset.woff2`}
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href={`${import.meta.env.BASE_URL}fonts/Ysabeau-Bold-subset.woff2`}
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href={`${import.meta.env.BASE_URL}fonts/Ysabeau-BoldItalic-subset.woff2`}
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
        <RouterHead />
      </head>
      <body lang="it" class="page-scrollbar">
        <RouterOutlet />
      </body>
    </QwikCityProvider>
  );
});
